<a href="https://colab.research.google.com/github/w-araujo-silva/projeto-grupo3/blob/wagner/wagner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd


# lendo o dataset
def carregar_banco_csv(file_path='/content/data_science_salaries.csv'):
    return pd.read_csv(file_path)

In [11]:
df = carregar_banco_csv()

In [12]:
df

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,company_size
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium
...,...,...,...,...,...,...,...,...,...,...,...
6594,Staff Data Analyst,Entry-level,Contract,Hybrid,2020,Canada,60000,CAD,44753,Canada,Large
6595,Staff Data Analyst,Executive-level,Full-time,On-site,2020,Nigeria,15000,USD,15000,Canada,Medium
6596,Machine Learning Manager,Senior-level,Full-time,Hybrid,2020,Canada,157000,CAD,117104,Canada,Large
6597,Data Engineer,Mid-level,Full-time,Hybrid,2020,Austria,65000,EUR,74130,Austria,Large
6598,Data Scientist,Senior-level,Full-time,On-site,2020,Austria,80000,EUR,91237,Austria,Small

In [ ]:
def media_salario(df):
    return round(df["salary_in_usd"].mean(), 2)

## Média Salarial em USD

In [ ]:
print(media_salario(df))

145560.56

## Conclusões
A média salarial no periodo foi de USD 145.560,56.

## Evolução temporal
Como os salários médios variaram de 2020 a 2024?

In [ ]:
cols = ['salary_in_usd']
cols2 = ['work_year']
df.groupby(cols2)[cols].mean()

           salary_in_usd
work_year
2020       102250.866667
2021        99501.287037
2022       131788.543165
2023       150791.420757
2024       153124.084063

## Conclusões
Houve uma redução no salário médio em 2021 em relação ao ano anterior, porém nos anos seguintes pode ser constatar uma crescente na média salarial.

## Evolução temporal
Média salarial por ano e modalidade de trabalho

In [ ]:
cols = ['salary_in_usd']
cols2 = ['work_models', 'work_year']
df.groupby(cols2)[cols].mean()

                       salary_in_usd
work_models work_year
Hybrid      2020        86879.142857
            2021        81180.958333
            2022        84869.150000
            2023        81467.600000
            2024       138333.000000
On-site     2020        94258.111111
            2021       106835.758621
            2022       134873.779310
            2023       155497.027260
            2024       156509.983834
Remote      2020       115214.083333
            2021       109121.843478
            2022       134176.040519
            2023       145490.165359
            2024       142561.492647

## Conclusões
Nas modalidades de trabalho presencial e remota é possível perceber uma crescente na média salárial, exceto no ano de 2021 na modalidade remota, onde houve uma redução em comparação ao ano anterior. Comparando ano a ano as modalidades presencial e remota, a modalidade presencial só possui média salarial inferior a remota nos anos de 2020 e 2021, possivelmente por haver mais funcionários na modalidade remota em decorrencia da pandemia de COVID 19, pois lidera nos demais anos. A modalidade hibrida apresentou oscilação nas médias salariais no decorrer dos anos, havendo um crescimento expressivo no ano de 2024.

## Evolução temporal
Houve mudanças significativas na modalidade de trabalho (mais remoto, menos remoto) no período?

In [ ]:
cols = ['salary_in_usd']
cols2 = ['work_models', 'work_year']
df.groupby(cols2)[cols].count()

                       salary_in_usd
work_models work_year
Hybrid      2020                  21
            2021                  72
            2022                  60
            2023                  70
            2024                   2
On-site     2020                  18
            2021                  29
            2022                 435
            2023                2898
            2024                 433
Remote      2020                  36
            2021                 115
            2022                 617
            2023                1657
            2024                 136

## Conclusões
Considerando o intervalo de 2020 até 2023 e desconsiderando o ano de 2024, pois possívelmente apresenta dados parciais, é possível perceber uma crescente na quantidade de funcionários nas modalidades de trabalho presencial e remoto. Nos anos de 2020 a 2022 a modalidade remota foi a mais praticada, possivelmente por conta da pandemia de COVID 19, porém em 2023 o trabalho presencial liderou como modalidade mais utilizada. A modalidade de trabalho hibrida apresenta a menor quantidade de adeptos em todos os anos quando comparada as demais modalidades.